version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/sample-python-ap/scripts

hooks:
  ApplicationStop:
    - location: stop_container.sh
      timeout: 60
      runas: ubuntu

  BeforeInstall:
    - location: cleanup.sh
      timeout: 60
      runas: ubuntu

  AfterInstall:
    - location: start_container.sh
      timeout: 60
      runas: ubuntu
