version: 0.0
os: linux

files:
  - source: scripts
    destination: /home/ubuntu/scripts

hooks:
  ApplicationStop:
    - location: /home/ubuntu/scripts/stop_container.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: /home/ubuntu/scripts/start_container.sh
      timeout: 300
      runas: root
