version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app  # adjust path as needed
hooks:
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ubuntu
